### ISSUE TITLE
TBC

### ISSUE THREAD

**Issue by cubrula** [RealLushen/FelwoodAlpha#10]
Dark Portal is Open and also the flight point from Isle of Quel Danas is avaiable.

**Comment by RealLushen** [comment]
Thanks for your Report, we will fix this asap :)

Best Regards,
Lushen

**Comment by RealLushen** [comment]
Sunwell Plateau
Magisters Terrace
Dark Portal
Demon Portal

Are now all blocked. Flight Path to Isle of Quel'thalas is still working but thats no problem since you can't get to TBC now anymore. :)
